spring:
  session:
    store-type: hazelcast
  data:
    mongodb:
      database: calvinus
security:
  basic:
    enabled: false
  oauth2:
      client:
        client-id: calvinus
        client-secret: KaE6pN
        scope: read,write
        auto-approve-scopes: '.*'

facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me